name: Update README
on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 0 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update  BASANTPANDEY POST
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          readme_path: ./README.md
          feed_list: "http://feeds.feedburner.com/aeyeinnovators/feeds"
          comment_tag_name: "BASANTPANDEY-POST-LIST"
          commit_message: "🤖♻️ Update README with BasantPandey' latest blog posts"
          max_post_count: "5"
          date_format: "mmm d, yyyy"
          template: '$newline- $date - [$title]($url)'
      - name: Update BASANTPANDEYYOUTUBE' YouTube videos
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          readme_path: ./README.md
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCLDanRvkpWTY-pqMyRyGTIw"
          comment_tag_name: "BASANTPANDEYYOUTUBE-POST-LIST"
          commit_message: "🤖♻️ Update README with BasantPandey' latest videos on YouTube channel"
          max_post_count: "5"
          date_format: "mmm d, yyyy"
          template: '$newline- $date - [$title]($url)'
